use book_inventory;

INSERT INTO `books`
    (`title`, `author`, `year`, `description`)
VALUES
    ('Classical Mythology', 'Mark P. O. Morford', 2002, 'Oxford University Press'),
    ('Clara Callan', 'Richard Bruce Wright', 2001, 'HarperFlamingo Canada'),
    ('Decision in Normandy', 'Carlo DEste', 1991, 'HarperPerennial'),
    ('Flu: The Story of the Great Influenza Pandemic of 1918 and the Search for the Virus That Caused It', 'Gina Bari Kolata', 1999, 'Farrar Straus Giroux'),
    ('The Mummies of Urumchi', 'E. J. W. Barber', 1999, 'W. W. Norton &amp,  Company'),
    ('The Kitchen Gods Wife', 'Amy Tan', 1991, 'Putnam Pub Group'),
    ('What If?: The Worlds Foremost Military Historians Imagine What Might Have Been', 'Robert Cowley', 2000, 'Berkley Publishing Group'),
    ('PLEADING GUILTY', 'Scott Turow', 1993, 'Audioworks'),
    ('Under the Black Flag: The Romance and the Reality of Life Among the Pirates', 'David Cordingly', 1996, 'Random House'),
    ('Where Youll Find Me: And Other Stories', 'Ann Beattie', 2002, 'Scribner'),
    ('Nights Below Station Street', 'David Adams Richards', 1988, 'Emblem Editions'),
    ('Hitlers Secret Bankers: The Myth of Swiss Neutrality During the Holocaust', 'Adam Lebor', 2000, 'Citadel Press'),
    ('The Middle Stories', 'Sheila Heti', 2004, 'House of Anansi Press'),
    ('Jane Doe', 'R. J. Kaiser', 1999, 'Mira Books'),
    ('A Second Chicken Soup for the Womans Soul (Chicken Soup for the Soul Series)', 'Jack Canfield', 1998, 'Health Communications'),
    ('The Witchfinder (Amos Walker Mystery Series)', 'Loren D. Estleman', 1998, 'Brilliance Audio - Trade'),
    ('More Cunning Than Man: A Social History of Rats and Man', 'Robert Hendrickson', 1999, 'Kensington Publishing Corp.'),
    ('Goodbye to the Buttermilk Sky', 'Julia Oliver', 1994, 'River City Pub'),
    ('The Testament', 'John Grisham', 1999, 'Dell'),
    ('Beloved (Plume Contemporary Fiction)', 'Toni Morrison', 1994, 'Plume'),
    ('Our Dumb Century: The Onion Presents 100 Years of Headlines from Americas Finest News Source', 'The Onion', 1999, 'Three Rivers Press'),
    ('New Vegetarian: Bold and Beautiful Recipes for Every Occasion', 'Celia Brooks Brown', 2001, 'Ryland Peters &amp,  Small Ltd'),
    ('If Id Known Then What I Know Now: Why Not Learn from the Mistakes of Others? : You Cant Afford to Make Them All Yourself', 'J. R. Parrish', 2003, 'Cypress House'),
    ('Mary-Kate &amp,  Ashley Switching Goals (Mary-Kate and Ashley Starring in)', 'Mary-Kate &amp,  Ashley Olsen', 2000, 'HarperEntertainment'),
    ('Tell Me This Isnt Happening', 'Robynn Clairday', 1999, 'Scholastic'),
    ('Flood : Mississippi 1927', 'Kathleen Duey', 1998, 'Aladdin'),
    ('Wild Animus', 'Rich Shapero', 2004, 'Too Far'),
    ('Airframe', 'Michael Crichton', 1997, 'Ballantine Books'),
    ('Timeline', 'MICHAEL CRICHTON', 2000, 'Ballantine Books'),
    ('OUT OF THE SILENT PLANET', 'C.S. Lewis', 1996, 'Scribner'),
    ('Prague : A Novel', 'ARTHUR PHILLIPS', 2003, 'Random House Trade Paperbacks'),
    ('Chocolate Jesus', 'Stephan Jaramillo', 1998, 'Berkley Publishing Group'),
    ('Wie Barney es sieht.', 'Mordecai Richler', 2002, 'Lebbe'),
    ('Der Fluch der Kaiserin. Ein Richter- Di- Roman.', 'Eleanor Cooney', 2001, 'Goldmann'),
    ('Sturmzeit. Roman.', 'Charlotte Link', 1991, 'Goldmann'),
    ('Tage der Unschuld.', 'Richard North Patterson', 2000, 'Goldmann'),
    ('Lying Awake', 'Mark Salzman', 2000, 'Alfred A. Knopf'),
    ('To Kill a Mockingbird', 'Harper Lee', 1988, 'Little Brown &amp,  Company'),
    ('Seabiscuit: An American Legend', 'LAURA HILLENBRAND', 2002, 'Ballantine Books'),
    ('Pigs in Heaven', 'Barbara Kingsolver', 1993, 'Harpercollins'),
    ('Miss Zukas and the Ravens Dance', 'Jo Dereske', 1996, 'Avon'),
    ('Pride and Prejudice', 'Jane Austen', 1983, 'Bantam'),
    ('The Therapeutic Touch: How to Use Your Hands to Help or to Heal', 'Dolores Krieger', 1979, 'Fireside'),
    ('Downtown', 'Anne Rivers Siddons', 1995, 'HarperTorch'),
    ('Icebound', 'Dean R. Koontz', 2000, 'Bantam Books'),
    ('Ill Be Seeing You', 'Mary Higgins Clark', 1994, 'Pocket'),
    ('From the Corner of His Eye', 'Dean Koontz', 2001, 'Bantam Books'),
    ('Isle of Dogs', 'Patricia Cornwell', 2002, 'Berkley Publishing Group'),
    ('Purity in Death', 'J.D. Robb', 2002, 'Berkley Publishing Group'),
    ('This Year It Will Be Different: And Other Stories', 'Maeve Binchy', 1997, 'Dell'),
    ('Proxies', 'Laura J. Mixon', 1999, 'Tor Books'),
    ('Left Behind: A Novel of the Earths Last Days (Left Behind #1)', 'Tim Lahaye', 2000, 'Tyndale House Publishers'),
    ('The Street Lawyer', 'JOHN GRISHAM', 1999, 'Dell'),
    ('Love, Medicine and Miracles', 'M.D. Bernie S. Siegel', 1988, 'HarperCollins Publishers'),
    ('All the Kings Men', 'Robert Penn Warren', 1982, 'Harvest Books');